# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(800, 560, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.ProductFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.ProductFrame1.setGeometry(QtCore.QRect(50, 90, 441, 121))
        self.ProductFrame1.setStyleSheet("QFrame {\n"
"    background: lightgray;\n"
"    border-radius: 30px;\n"
"}")
        self.ProductFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProductFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProductFrame1.setObjectName("ProductFrame1")
        self.BuyingButton1 = QtWidgets.QPushButton(self.ProductFrame1)
        self.BuyingButton1.setGeometry(QtCore.QRect(310, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.BuyingButton1.setFont(font)
        self.BuyingButton1.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: red;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: darkred;\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.BuyingButton1.setObjectName("BuyingButton1")
        self.CartProductAmount1 = QtWidgets.QLabel(self.ProductFrame1)
        self.CartProductAmount1.setGeometry(QtCore.QRect(310, 50, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductAmount1.setFont(font)
        self.CartProductAmount1.setAlignment(QtCore.Qt.AlignCenter)
        self.CartProductAmount1.setObjectName("CartProductAmount1")
        self.CartProductIncrease1 = QtWidgets.QPushButton(self.ProductFrame1)
        self.CartProductIncrease1.setGeometry(QtCore.QRect(400, 40, 21, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.CartProductIncrease1.setFont(font)
        self.CartProductIncrease1.setStyleSheet("QPushButton {\n"
"    background: lightgray;\n"
"}")
        self.CartProductIncrease1.setObjectName("CartProductIncrease1")
        self.CartProductDecrease1 = QtWidgets.QPushButton(self.ProductFrame1)
        self.CartProductDecrease1.setGeometry(QtCore.QRect(310, 40, 21, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.CartProductDecrease1.setFont(font)
        self.CartProductDecrease1.setStyleSheet("QPushButton {\n"
"    background: lightgray;\n"
"}")
        self.CartProductDecrease1.setObjectName("CartProductDecrease1")
        self.CartProductLabel1 = QtWidgets.QLabel(self.ProductFrame1)
        self.CartProductLabel1.setGeometry(QtCore.QRect(170, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductLabel1.setFont(font)
        self.CartProductLabel1.setText("")
        self.CartProductLabel1.setObjectName("CartProductLabel1")
        self.CartProductPicture1 = QtWidgets.QLabel(self.ProductFrame1)
        self.CartProductPicture1.setGeometry(QtCore.QRect(20, 20, 131, 91))
        self.CartProductPicture1.setStyleSheet("QLabel {\n"
"    image: url(:/)\n"
"}")
        self.CartProductPicture1.setText("")
        self.CartProductPicture1.setObjectName("CartProductPicture1")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(40, 570, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: #64AB25;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.SearchButton.setObjectName("SearchButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cart:"))
        self.pushButton_2.setText(_translate("MainWindow", "Check out"))
        self.BuyingButton1.setText(_translate("MainWindow", "Delete"))
        self.CartProductAmount1.setText(_translate("MainWindow", "Buy: 1"))
        self.CartProductIncrease1.setText(_translate("MainWindow", "+"))
        self.CartProductDecrease1.setText(_translate("MainWindow", "-"))
        self.SearchButton.setText(_translate("MainWindow", "Go Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
