# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 684)
        MainWindow.setStyleSheet("QWidget {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #07C25C, stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #717072;\n"
"    border-bottom: 1px solid #717072;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 30, 271, 131))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(72)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 150, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 210, 731, 71))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.LoginFrame = QtWidgets.QFrame(self.centralwidget)
        self.LoginFrame.setGeometry(QtCore.QRect(390, 320, 251, 281))
        self.LoginFrame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LoginFrame.setStyleSheet("QFrame {\n"
"    background: black;\n"
"    border-radius: 20px;\n"
"}")
        self.LoginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginFrame.setObjectName("LoginFrame")
        self.LoginButton = QtWidgets.QPushButton(self.LoginFrame)
        self.LoginButton.setGeometry(QtCore.QRect(110, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.LoginButton.setFont(font)
        self.LoginButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: #64AB25;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.LoginButton.setObjectName("LoginButton")
        self.Password = QtWidgets.QLineEdit(self.LoginFrame)
        self.Password.setGeometry(QtCore.QRect(30, 140, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password.setFont(font)
        self.Password.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #717072;\n"
"    border-bottom: 1px solid #717072;\n"
"}")
        self.Password.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.Password.setInputMask("")
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setDragEnabled(True)
        self.Password.setClearButtonEnabled(True)
        self.Password.setObjectName("Password")
        self.Username = QtWidgets.QLineEdit(self.LoginFrame)
        self.Username.setGeometry(QtCore.QRect(30, 100, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Username.setFont(font)
        self.Username.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Username.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Username.setStyleSheet("")
        self.Username.setText("")
        self.Username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Username.setCursorPosition(0)
        self.Username.setDragEnabled(True)
        self.Username.setReadOnly(False)
        self.Username.setClearButtonEnabled(True)
        self.Username.setObjectName("Username")
        self.CreateAccountButton = QtWidgets.QPushButton(self.LoginFrame)
        self.CreateAccountButton.setGeometry(QtCore.QRect(110, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CreateAccountButton.setFont(font)
        self.CreateAccountButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: #64AB25;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}")
        self.CreateAccountButton.setObjectName("CreateAccountButton")
        self.LoginLabel = QtWidgets.QLabel(self.LoginFrame)
        self.LoginLabel.setGeometry(QtCore.QRect(0, 30, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(22)
        font.setBold(False)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setStyleSheet("QLabel {\n"
"    color: white\n"
"}")
        self.LoginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LoginLabel.setObjectName("LoginLabel")
        self.LoginButton.raise_()
        self.Password.raise_()
        self.CreateAccountButton.raise_()
        self.LoginLabel.raise_()
        self.Username.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Fresh"))
        self.label_2.setText(_translate("MainWindow", "Welcome to Fresh! We only sell fresh stuff here. "))
        self.label_3.setText(_translate("MainWindow", "Please log in or register an account if you don\'t have one before start using."))
        self.LoginButton.setText(_translate("MainWindow", "Login"))
        self.Password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Username.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.CreateAccountButton.setText(_translate("MainWindow", "Create Account"))
        self.LoginLabel.setText(_translate("MainWindow", "Account Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
