# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PageLabel = QtWidgets.QLabel(self.centralwidget)
        self.PageLabel.setGeometry(QtCore.QRect(30, 10, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.PageLabel.setFont(font)
        self.PageLabel.setStyleSheet("color: white;\n"
"background-color : \"rgb(0, 0, 0)\";\n"
"border-radius: 15px;\n"
"")
        self.PageLabel.setObjectName("PageLabel")
        self.ConfirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmButton.setGeometry(QtCore.QRect(270, 330, 75, 24))
        self.ConfirmButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: #64AB25;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}")
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.InfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.InfoLabel.setGeometry(QtCore.QRect(40, 80, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InfoLabel.setFont(font)
        self.InfoLabel.setObjectName("InfoLabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 120, 591, 181))
        self.frame.setStyleSheet("background-color: rgb(116, 183, 46);\n"
"border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.UsernameLabel = QtWidgets.QLabel(self.frame)
        self.UsernameLabel.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.PasswordLabel = QtWidgets.QLabel(self.frame)
        self.PasswordLabel.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.RePasswordLabel = QtWidgets.QLabel(self.frame)
        self.RePasswordLabel.setGeometry(QtCore.QRect(20, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RePasswordLabel.setFont(font)
        self.RePasswordLabel.setObjectName("RePasswordLabel")
        self.UsernameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.UsernameLineEdit.setGeometry(QtCore.QRect(140, 20, 411, 31))
        self.UsernameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UsernameLineEdit.setObjectName("UsernameLineEdit")
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(140, 70, 411, 31))
        self.PasswordLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.RePasswordLineEdit = QtWidgets.QLineEdit(self.frame)
        self.RePasswordLineEdit.setGeometry(QtCore.QRect(140, 120, 411, 31))
        self.RePasswordLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.RePasswordLineEdit.setObjectName("RePasswordLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PageLabel.setText(_translate("MainWindow", "Register page"))
        self.ConfirmButton.setText(_translate("MainWindow", "Confirm"))
        self.InfoLabel.setText(_translate("MainWindow", "Please fill in below to register a new account."))
        self.UsernameLabel.setText(_translate("MainWindow", "Username:"))
        self.PasswordLabel.setText(_translate("MainWindow", "Password:"))
        self.RePasswordLabel.setText(_translate("MainWindow", "Re-Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
