# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sell_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ConfirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmButton.setGeometry(QtCore.QRect(290, 420, 75, 24))
        self.ConfirmButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: #64AB25;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}")
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 90, 591, 301))
        self.frame.setStyleSheet("background-color: rgb(116, 183, 46);\n"
"border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.NameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.NameLineEdit.setGeometry(QtCore.QRect(150, 20, 411, 31))
        self.NameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.PriceLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PriceLineEdit.setGeometry(QtCore.QRect(150, 70, 411, 31))
        self.PriceLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PriceLineEdit.setObjectName("PriceLineEdit")
        self.DetailTextEdit = QtWidgets.QTextEdit(self.frame)
        self.DetailTextEdit.setGeometry(QtCore.QRect(150, 120, 411, 71))
        self.DetailTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DetailTextEdit.setObjectName("DetailTextEdit")
        self.VegetableCategory = QtWidgets.QRadioButton(self.frame)
        self.VegetableCategory.setGeometry(QtCore.QRect(150, 220, 101, 20))
        self.VegetableCategory.setObjectName("VegetableCategory")
        self.FruitCategory = QtWidgets.QRadioButton(self.frame)
        self.FruitCategory.setGeometry(QtCore.QRect(330, 220, 89, 20))
        self.FruitCategory.setObjectName("FruitCategory")
        self.DailyProductCategory = QtWidgets.QRadioButton(self.frame)
        self.DailyProductCategory.setGeometry(QtCore.QRect(150, 260, 111, 20))
        self.DailyProductCategory.setObjectName("DailyProductCategory")
        self.OTOPCategory = QtWidgets.QRadioButton(self.frame)
        self.OTOPCategory.setGeometry(QtCore.QRect(330, 260, 89, 20))
        self.OTOPCategory.setObjectName("OTOPCategory")
        self.PriceLabel = QtWidgets.QLabel(self.frame)
        self.PriceLabel.setGeometry(QtCore.QRect(20, 50, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.PriceLabel.setFont(font)
        self.PriceLabel.setObjectName("PriceLabel")
        self.NameLabel = QtWidgets.QLabel(self.frame)
        self.NameLabel.setGeometry(QtCore.QRect(20, 0, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.DetailLabel = QtWidgets.QLabel(self.frame)
        self.DetailLabel.setGeometry(QtCore.QRect(20, 110, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.DetailLabel.setFont(font)
        self.DetailLabel.setObjectName("DetailLabel")
        self.CategoryLabel = QtWidgets.QLabel(self.frame)
        self.CategoryLabel.setGeometry(QtCore.QRect(20, 190, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(16)
        self.CategoryLabel.setFont(font)
        self.CategoryLabel.setObjectName("CategoryLabel")
        self.PageLabel = QtWidgets.QLabel(self.centralwidget)
        self.PageLabel.setGeometry(QtCore.QRect(30, 10, 531, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(48)
        self.PageLabel.setFont(font)
        self.PageLabel.setStyleSheet("color: white;\n"
"background-color : \"rgb(0, 0, 0)\";\n"
"border-radius: 15px;\n"
"")
        self.PageLabel.setObjectName("PageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConfirmButton.setText(_translate("MainWindow", "Confirm"))
        self.DetailTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.VegetableCategory.setText(_translate("MainWindow", "Vegetable"))
        self.FruitCategory.setText(_translate("MainWindow", "Fruit"))
        self.DailyProductCategory.setText(_translate("MainWindow", "Daily product"))
        self.OTOPCategory.setText(_translate("MainWindow", "OTOP"))
        self.PriceLabel.setText(_translate("MainWindow", "Price"))
        self.NameLabel.setText(_translate("MainWindow", "Product Name"))
        self.DetailLabel.setText(_translate("MainWindow", "Detail"))
        self.CategoryLabel.setText(_translate("MainWindow", "Category"))
        self.PageLabel.setText(_translate("MainWindow", "Sell your product here:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
